# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
 
stages:
  - stage: Test
    jobs:
      - job: Test

  - stage: Build
    jobs:
      - deployment:

        pool:
          vmImage: 'windows-latest'
        environment: TIGSQLDEMO_DEV1_Environment_Approvers
        strategy:
         runOnce:
            deploy:
              steps:
                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: 'TiGDEMOSQL_ServerConnection1'
                    KeyVaultName: 'tigsql-keyvault-01'
                    SecretsFilter: 'LocalAdmin2'
                    RunAsPreJob: false

                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'TiGDEMOSQL_ServerConnection1'
                    subscriptionId: '97b1d573-01f6-4493-9ed7-22fc75e79016'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'tigsql-rg01'
                    location: 'UK South'
                    templateLocation: 'Linked artifact'
                    csmFile: 'azuredeploy.json'
                    csmParametersFile: 'azuredeploy.parameters.json'
                    overrideParameters: '-adminPassword $(LocalAdmin2)'
                    deploymentMode: 'Incremental'
                    deploymentName: 'TemplateDeploy'