# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build Development Environment Approval
    dependsOn: build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: publishinternal
        displayName: 'TIGSQLDEMO_DEV1_PIPELINES_APPROVAL'
        environment: TIGDEVDEMO_DEV1_Environmentme: 'TemplateDeploy'